# Generated by Django 3.1.7 on 2021-03-24 08:56

from django.db import migrations, models


def populate_city(apps, schema_editor):
    City = apps.get_model('utils', 'City')
    City.objects.create(title='Астана')
    City.objects.create(title='Алматы')

def populate_day_of_week(apps, schema_editor):
    DayOfWeek = apps.get_model('utils', 'DayOfWeek')
    days = ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"]
    for day in days:
        DayOfWeek.objects.create(title=day)



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(populate_city),
        migrations.RunPython(populate_day_of_week)
    ]
